language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: xX/oYCtz+Srndz56r6INRtWWZRWsbUkjRnGdqaUcn6Y8tz71P3Vj2smHQxUZKRYMVJ6wopN+HADiudTxxXKqMvmqKZj+p2iGWoWlMShEG50GspSqq+mTJT/LWoMnmBuqR+IOyb2AzGm91epVOrqJUldNNGDn66VrCcqUYc/GvhmEm63gVCDh4vcXivPkxh05ccZU4edb0m29fme+DQGViVCXuoDjWRt1ej4y23RSH8dPEi5GTzcrwJQ+hkG5LRo1ctzBuRsUaNTvfdYGfTgyG5FFcrDz7SxzHQrAGgFc+YZq7px8KgeDuUUD819cc7XucnnR+CkfxjvbTDA8p6AeikR9RHlLo/A5x/UtAzONGdqb2DfmpzXKZ3rXdcPDqtDTjY8RH1U25c9enhY8fJsoqbxOGqWyWCBW3DET7x1tdO8ngXL4/lXRfTGgYCzCc18J+w6OPZZru/0dkeGpX3uP5wkAfqXYYVAvLh9sbv3Y74kFi5Jj4AMaxT+b4A5AxokKEe089rn8PxfVbpZLa7Sbw0uU3uXNknXkRV2amdIumgk87EiRxhfjZhGgSSrmi7vt0zHFmE6b79VZXm18B/4cB/00VZDOZy8HvQVLerdEFPZ2xzvw+WDkTAIvEor9oUYHlQA04MqW4wdGbDwhpZXLNcWsSLfukamED3GaafmMmCU=
  app: radiant-refuge-58794
  on:
    repo: aomnes/projet_ruby
